name: Tạo bộ lọc Bromite
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - uses: actions/checkout@v3
      - name: Build filters 
        run: bash build.sh

      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV
        
      - name: Commit filters 
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'filters.dat'
          default_author: github_actor 
          message: 'Cập nhật bộ lọc: ${{ env.DATE }}'
          
      - name: Release filters list
        uses: softprops/action-gh-release@v1
        with:
          files: filters.dat
          name: Bộ lọc ${{ env.DATE }}
          tag_name: ${{ env.DATE }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete:
    name: 'Complete'
    runs-on: ubuntu-22.04
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
          
