# This is a basic workflow to help you get started with Actions

name: update tool

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          wget https://github.com/bromite/bromite/releases/latest/download/ruleset_converter
          
          
      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV
        
      - name: Commit tool 
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'ruleset_converter'
          default_author: github_actions 
          message: 'Cập nhật tool: ${{ env.DATE }}'
          push: true